// Generated by tishlang_compile_js
let canvases = {  };
let pending = [];
let gpuState = "none";
let device = null;
let format = null;
let wavePipeline = null;
let barPipeline = null;
let SHADER = "struct VOut {\n  @builtin(position) pos : vec4<f32>,\n  @location(0) col : vec4<f32>,\n};\n@vertex fn vs(@location(0) p : vec2<f32>, @location(1) c : vec4<f32>) -> VOut {\n  var o : VOut;\n  o.pos = vec4<f32>(p, 0.0, 1.0);\n  o.col = c;\n  return o;\n}\n@fragment fn fs(@location(0) c : vec4<f32>) -> @location(0) vec4<f32> {\n  return c;\n}\n";
function hexToRgb (hex) {
  {
    let h = (hex ? (String(hex) ?? null) : "#22d3ee");
    if (((h.length > 0) && ((h.substring(0, 1) ?? null) === "#")))
      {
        (h = (h.substring(1) ?? null));
      }
    let r = ((parseInt((h.substring(0, 2) ?? null), 16) ?? null) / 255);
    let g = ((parseInt((h.substring(2, 4) ?? null), 16) ?? null) / 255);
    let b = ((parseInt((h.substring(4, 6) ?? null), 16) ?? null) / 255);
    if ((r !== r))
      {
        (r = 0.13);
      }
    if ((g !== g))
      {
        (g = 0.83);
      }
    if ((b !== b))
      {
        (b = 0.93);
      }
    return [r, g, b];
  }
}
function buildPipelines () {
  {
    let mod = (device.createShaderModule({ code: SHADER }) ?? null);
    let vbl = { arrayStride: 24, attributes: [{ shaderLocation: 0, offset: 0, format: "float32x2" }, { shaderLocation: 1, offset: 8, format: "float32x4" }] };
    let blend = { color: { srcFactor: "one", dstFactor: "one-minus-src-alpha", operation: "add" }, alpha: { srcFactor: "one", dstFactor: "one-minus-src-alpha", operation: "add" } };
    let tgt = { format: format, blend: blend };
    (wavePipeline = (device.createRenderPipeline({ layout: "auto", vertex: { module: mod, entryPoint: "vs", buffers: [vbl] }, fragment: { module: mod, entryPoint: "fs", targets: [tgt] }, primitive: { topology: "line-strip" } }) ?? null));
    (barPipeline = (device.createRenderPipeline({ layout: "auto", vertex: { module: mod, entryPoint: "vs", buffers: [vbl] }, fragment: { module: mod, entryPoint: "fs", targets: [tgt] }, primitive: { topology: "triangle-list" } }) ?? null));
  }
}
function flushPending () {
  {
    let q = pending;
    (pending = []);
    let i = 0;
    while ((i < q.length))
      {
        let p = (q[i] ?? null);
        (doRegister(p.id, p.canvas, p.cssW, p.cssH, p.dpr) ?? null);
        (i = (i + 1));
      }
  }
}
function initGpu () {
  {
    if ((gpuState !== "none"))
      {
        return;
      }
    if (((((__v) => __v == null ? "null" : typeof __v)(navigator) === "undefined") || !navigator.gpu))
      {
        (gpuState = "failed");
        return;
      }
    (gpuState = "init");
    ((navigator.gpu.requestAdapter() ?? null).then((adapter) => {
      {
        if (!adapter)
          {
            (gpuState = "failed");
            (flushPending() ?? null);
            return;
          }
        ((adapter.requestDevice() ?? null).then((dev) => {
          {
            (device = dev);
            (format = (navigator.gpu.getPreferredCanvasFormat() ?? null));
            try {
              {
                (buildPipelines() ?? null);
                (gpuState = "ready");
              }
            } catch (e) {
              {
                (gpuState = "failed");
              }
            }
            (flushPending() ?? null);
          }
        }, (e) => {
          {
            (gpuState = "failed");
            (flushPending() ?? null);
          }
        }) ?? null);
      }
    }, (e) => {
      {
        (gpuState = "failed");
        (flushPending() ?? null);
      }
    }) ?? null);
  }
}
function waveVerts (buf, color) {
  {
    let N = buf.length;
    let rgb = (hexToRgb(color) ?? null);
    let out = (new Float32Array((N * 6)) ?? null);
    let i = 0;
    while ((i < N))
      {
        let v = ((buf[i] ?? null) / 128);
        let x = (((i / (N - 1)) * 2) - 1);
        let dev = (((v - 1) * 3.5) * 0.46);
        if ((dev > 0.48))
          {
            (dev = 0.48);
          }
        else
          if ((dev < -0.48))
            {
              (dev = -0.48);
            }
        let y = (dev * 2);
        let o = (i * 6);
        (out[o] = x);
        (out[(o + 1)] = y);
        (out[(o + 2)] = (rgb[0] ?? null));
        (out[(o + 3)] = (rgb[1] ?? null));
        (out[(o + 4)] = (rgb[2] ?? null));
        (out[(o + 5)] = 1);
        (i = (i + 1));
      }
    return out;
  }
}
function pushVert (out, oi, x, y, r, g, b, a) {
  {
    (out[oi] = x);
    (out[(oi + 1)] = y);
    (out[(oi + 2)] = r);
    (out[(oi + 3)] = g);
    (out[(oi + 4)] = b);
    (out[(oi + 5)] = a);
    return (oi + 6);
  }
}
function spectrumVerts (buf, color, w, h) {
  {
    let n = buf.length;
    let rgb = (hexToRgb(color) ?? null);
    let bars = 72;
    if ((bars > n))
      {
        (bars = n);
      }
    let out = (new Float32Array(((bars * 6) * 6)) ?? null);
    let gapPx = 2;
    let bwidPx = ((w - ((bars - 1) * gapPx)) / bars);
    if ((bwidPx < 1))
      {
        (bwidPx = 1);
      }
    let count = 0;
    let oi = 0;
    let bi = 0;
    while ((bi < bars))
      {
        let src = (Math.floor(((bi / bars) * (n * 0.7))) ?? null);
        let val = ((buf[src] ?? null) / 255);
        let bhPx = (Math.max(1, (val * h)) ?? null);
        let xPx = (bi * (bwidPx + gapPx));
        let x0 = (((xPx / w) * 2) - 1);
        let x1 = ((((xPx + bwidPx) / w) * 2) - 1);
        let yTop = (1 - (2 * ((h - bhPx) / h)));
        let yBot = -1;
        let a = (0.35 + (val * 0.6));
        if ((a > 1))
          {
            (a = 1);
          }
        let r = ((rgb[0] ?? null) * a);
        let g = ((rgb[1] ?? null) * a);
        let b = ((rgb[2] ?? null) * a);
        (oi = (pushVert(out, oi, x0, yBot, r, g, b, a) ?? null));
        (oi = (pushVert(out, oi, x1, yBot, r, g, b, a) ?? null));
        (oi = (pushVert(out, oi, x1, yTop, r, g, b, a) ?? null));
        (oi = (pushVert(out, oi, x0, yBot, r, g, b, a) ?? null));
        (oi = (pushVert(out, oi, x1, yTop, r, g, b, a) ?? null));
        (oi = (pushVert(out, oi, x0, yTop, r, g, b, a) ?? null));
        (count = (count + 6));
        (bi = (bi + 1));
      }
    return { verts: out, count: count };
  }
}
function drawGpu (c, f) {
  {
    let isWave = (f.kind === "wave");
    let verts = null;
    let count = 0;
    if (isWave)
      {
        (verts = (waveVerts(f.data, f.color) ?? null));
        (count = f.data.length);
      }
    else
      {
        let r = (spectrumVerts(f.data, f.color, c.w, c.h) ?? null);
        (verts = r.verts);
        (count = r.count);
      }
    if ((count < 2))
      {
        return;
      }
    let bytes = verts.byteLength;
    if ((!c.vbuf || (c.vcap < bytes)))
      {
        if (c.vbuf)
          {
            (c.vbuf.destroy() ?? null);
          }
        (c.vbuf = (device.createBuffer({ size: bytes, usage: (GPUBufferUsage.VERTEX | GPUBufferUsage.COPY_DST) }) ?? null));
        (c.vcap = bytes);
      }
    (device.queue.writeBuffer(c.vbuf, 0, verts) ?? null);
    let tex = null;
    try {
      {
        (tex = (c.ctx.getCurrentTexture() ?? null));
      }
    } catch (e) {
      {
        return;
      }
    }
    let enc = (device.createCommandEncoder() ?? null);
    let pass = (enc.beginRenderPass({ colorAttachments: [{ view: (tex.createView() ?? null), clearValue: { r: 0, g: 0, b: 0, a: 0 }, loadOp: "clear", storeOp: "store" }] }) ?? null);
    (pass.setPipeline((isWave ? wavePipeline : barPipeline)) ?? null);
    (pass.setVertexBuffer(0, c.vbuf) ?? null);
    (pass.draw(count) ?? null);
    (pass.end() ?? null);
    (device.queue.submit([(enc.finish() ?? null)]) ?? null);
  }
}
function drawWave2d (c, buf, hexColor) {
  {
    let ctx = c.ctx;
    let w = c.cssW;
    let h = c.cssH;
    let N = buf.length;
    if ((!ctx || (N < 2)))
      {
        return;
      }
    (ctx.setTransform(c.dpr, 0, 0, c.dpr, 0, 0) ?? null);
    (ctx.clearRect(0, 0, w, h) ?? null);
    let col = (hexColor ? hexColor : "#22d3ee");
    (ctx.beginPath() ?? null);
    let maxDev = (h * 0.48);
    let i = 0;
    while ((i < N))
      {
        let v = ((buf[i] ?? null) / 128);
        let x = ((i / (N - 1)) * w);
        let dev = ((((v - 1) * 3.5) * h) * 0.46);
        if ((dev > maxDev))
          {
            (dev = maxDev);
          }
        else
          if ((dev < (0 - maxDev)))
            {
              (dev = (0 - maxDev));
            }
        let y = ((h * 0.5) - dev);
        if ((i === 0))
          {
            (ctx.moveTo(x, y) ?? null);
          }
        else
          {
            (ctx.lineTo(x, y) ?? null);
          }
        (i = (i + 1));
      }
    (ctx.strokeStyle = col);
    (ctx.lineWidth = 1.3);
    (ctx.lineJoin = "round");
    (ctx.lineCap = "round");
    (ctx.shadowColor = col);
    (ctx.shadowBlur = 4);
    (ctx.stroke() ?? null);
    (ctx.shadowBlur = 0);
  }
}
function drawSpectrum2d (c, buf, hexColor) {
  {
    let ctx = c.ctx;
    let w = c.cssW;
    let h = c.cssH;
    let n = buf.length;
    if ((!ctx || (n < 1)))
      {
        return;
      }
    (ctx.setTransform(c.dpr, 0, 0, c.dpr, 0, 0) ?? null);
    (ctx.clearRect(0, 0, w, h) ?? null);
    let col = (hexColor ? hexColor : "#f97316");
    let bars = 72;
    if ((bars > n))
      {
        (bars = n);
      }
    let gap = 2;
    let bwid = ((w - ((bars - 1) * gap)) / bars);
    if ((bwid < 1))
      {
        (bwid = 1);
      }
    let bi = 0;
    while ((bi < bars))
      {
        let src = (Math.floor(((bi / bars) * (n * 0.7))) ?? null);
        let v = ((buf[src] ?? null) / 255);
        let bh2 = (Math.max(1, (v * h)) ?? null);
        let x = (bi * (bwid + gap));
        let y = (h - bh2);
        (ctx.fillStyle = col);
        (ctx.globalAlpha = (0.35 + (v * 0.6)));
        (ctx.fillRect(x, y, bwid, bh2) ?? null);
        (bi = (bi + 1));
      }
    (ctx.globalAlpha = 1);
  }
}
function doRegister (id, off, cssW, cssH, dpr) {
  {
    let pxW = (Math.max(1, (Math.floor((cssW * dpr)) ?? null)) ?? null);
    let pxH = (Math.max(1, (Math.floor((cssH * dpr)) ?? null)) ?? null);
    (off.width = pxW);
    (off.height = pxH);
    if ((gpuState === "ready"))
      {
        let cx = null;
        try {
          {
            (cx = (off.getContext("webgpu") ?? null));
          }
        } catch (e) {
          {
            (cx = null);
          }
        }
        if (cx)
          {
            try {
              {
                (cx.configure({ device: device, format: format, alphaMode: "premultiplied" }) ?? null);
                (canvases[id] = { kind: "gpu", ctx: cx, w: pxW, h: pxH, vbuf: null, vcap: 0 });
                return;
              }
            } catch (e) {
              {
                (cx = null);
              }
            }
          }
      }
    let c2 = null;
    try {
      {
        (c2 = (off.getContext("2d") ?? null));
      }
    } catch (e) {
      {
        (c2 = null);
      }
    }
    if (c2)
      {
        (canvases[id] = { kind: "2d", ctx: c2, cssW: cssW, cssH: cssH, dpr: dpr });
      }
  }
}
function onRegister (m) {
  {
    if ((gpuState === "none"))
      {
        (initGpu() ?? null);
      }
    if ((gpuState === "init"))
      {
        (pending.push({ id: m.id, canvas: m.canvas, cssW: m.cssW, cssH: m.cssH, dpr: m.dpr }) ?? null);
        return;
      }
    (doRegister(m.id, m.canvas, m.cssW, m.cssH, m.dpr) ?? null);
  }
}
function onFrame (frames) {
  {
    let i = 0;
    while ((i < frames.length))
      {
        let f = (frames[i] ?? null);
        let c = (canvases[f.id] ?? null);
        if (c)
          {
            if ((c.kind === "gpu"))
              {
                try {
                  {
                    (drawGpu(c, f) ?? null);
                  }
                } catch (e) {
                  {
                  }
                }
              }
            else
              {
                if ((f.kind === "wave"))
                  {
                    (drawWave2d(c, f.data, f.color) ?? null);
                  }
                else
                  {
                    (drawSpectrum2d(c, f.data, f.color) ?? null);
                  }
              }
          }
        (i = (i + 1));
      }
  }
}
function handle (e) {
  {
    let m = e.data;
    if (!m)
      {
        return;
      }
    if ((m.type === "register"))
      {
        (onRegister(m) ?? null);
      }
    else
      if ((m.type === "frame"))
        {
          (onFrame((m.frames ? m.frames : [])) ?? null);
        }
  }
}
(self.onmessage = handle);
