/** Shared docs page catalog — used by build-docs.mjs and build-og.mjs */
export const pages = [
  {
    slug: "",
    section: "Introduction",
    title: "Deckard Documentation",
    description: "Token-streamed live-coding DAW — humans and LLM agents co-DJ in deck.",
    content: "content/docs/index.md",
  },
  {
    slug: "getting-started/install",
    section: "Getting Started",
    title: "Install & run",
    description: "Dev server, static build, and deploy overview.",
    content: "content/docs/getting-started/install.md",
  },
  {
    slug: "getting-started/co-dj",
    section: "Getting Started",
    title: "Co-DJ quickstart",
    description: "Gateway + agent worker + browser loop.",
    content: "content/docs/getting-started/co-dj.md",
  },
  {
    slug: "deck/overview",
    section: "Deck language",
    title: "deck overview",
    description: "What a .deck file is, naming, and how it drives the DAW.",
    content: "content/docs/deck/overview.md",
  },
  {
    slug: "deck/grammar",
    section: "Deck language",
    title: "deck grammar",
    description: "Full streamable patch language reference (@spacedevin/deck).",
    source: "node_modules/@spacedevin/deck/docs/DECK_GRAMMAR.md",
  },
  {
    slug: "deck/host",
    section: "Deck language",
    title: "Deckard host overlay",
    description: "UI, ownership, clamps, and generator spellings on top of @spacedevin/deck.",
    source: "docs/DECK_GRAMMAR.md",
  },
  {
    slug: "deck/agent-grammar",
    section: "Deck language",
    title: "Agent grammar subset",
    description: "Lines a co-DJ lane may emit.",
    source: "docs/DECK_AGENT_GRAMMAR.md",
  },
  {
    slug: "deck/extensions",
    section: "Deck language",
    title: "Generator extensions",
    description: "gen_block patch / matrix graphs in Deckard.",
    source: "docs/DECK_EXTENSION.md",
  },
  {
    slug: "agents/overview",
    section: "Co-DJ / Agents",
    title: "Agent contract",
    description: "Surfaces agents should edit; invariants.",
    content: "content/docs/agents/overview.md",
  },
  {
    slug: "agents/websocket",
    section: "Co-DJ / Agents",
    title: "WebSocket & actors",
    description: "Gateway join, presence, deck.line / deck.block.",
    source: "docs/WS_AND_AGENTS.md",
  },
  {
    slug: "agents/stream-protocol",
    section: "Co-DJ / Agents",
    title: "Stream protocol",
    description: "Envelope, scheduling, control ops.",
    source: "docs/STREAM_PROTOCOL.md",
  },
  {
    slug: "agents/skills",
    section: "Co-DJ / Agents",
    title: "DJ skills & gating",
    description: "master_mixer denylist and skill IDs.",
    source: "docs/DJ_SKILLS.md",
  },
  {
    slug: "agents/roles",
    section: "Co-DJ / Agents",
    title: "Roles & skill files",
    description: "Host/client roles and skills/*.md composition.",
    source: "skills/README.md",
  },
  {
    slug: "architecture/overview",
    section: "Architecture",
    title: "Architecture",
    description: "Vision, subsystems, end-to-end signal path.",
    source: "docs/ARCHITECTURE.md",
  },
  {
    slug: "architecture/generators",
    section: "Architecture",
    title: "Generators",
    description: "Adding and wiring instrument modules.",
    source: "docs/GENERATORS.md",
  },
  {
    slug: "reference/author-tagging",
    section: "Reference",
    title: "Author tagging",
    description: "Who wrote which stems.",
    source: "docs/AUTHOR_TAGGING.md",
  },
  {
    slug: "reference/token-stream-demo",
    section: "Reference",
    title: "Token stream demo",
    description: "Offline demo of streaming deck into the hub.",
    source: "docs/TOKEN_STREAM_DEMO.md",
  },
]
