// Generated by tishlang_compile_js
let p = ((((__v) => __v == null ? "null" : typeof __v)(process) !== "undefined") ? process : null);
if (((p == null) || !p.stdin))
  {
    (console.error("This script must be compiled to JS and run with Node.js.") ?? null);
    if (p)
      (p.exit(1) ?? null);
  }
let GATEWAY_URL = "ws://127.0.0.1:35987";
let SESSION_ID = "default";
let ACTOR_ID = "actor-mcp";
if ((p.env && (p.env["CODJ_HUB_URL"] ?? null)))
  (GATEWAY_URL = (p.env["CODJ_HUB_URL"] ?? null));
if ((p.env && (p.env["CODJ_SESSION_ID"] ?? null)))
  (SESSION_ID = (p.env["CODJ_SESSION_ID"] ?? null));
if ((p.env && (p.env["CODJ_ACTOR_ID"] ?? null)))
  (ACTOR_ID = (p.env["CODJ_ACTOR_ID"] ?? null));
let tplBuffer = [];
let BUFFER_MAX_LINES = 1000;
function pushContextLine (line) {
  {
    if ((((__v) => __v == null ? "null" : typeof __v)(line) !== "string"))
      return;
    (tplBuffer.push(line) ?? null);
    if ((tplBuffer.length > BUFFER_MAX_LINES))
      {
        let newBuf = [];
        let i = (tplBuffer.length - BUFFER_MAX_LINES);
        while ((i < tplBuffer.length))
          {
            (newBuf.push((tplBuffer[i] ?? null)) ?? null);
            (i = (i + 1));
          }
        (tplBuffer = newBuf);
      }
  }
}
let ws = null;
let isConnected = false;
function connectToGateway () {
  {
    if ((((__v) => __v == null ? "null" : typeof __v)(WebSocket) === "undefined"))
      {
        (console.error("Node.js built-in WebSocket is required (Node v22+).") ?? null);
        return;
      }
    (ws = (new WebSocket(GATEWAY_URL) ?? null));
    (ws.onopen = (e) => {
      {
        (isConnected = true);
        let joinPayload = (JSON.stringify({ type: "join", sessionId: SESSION_ID, actorId: ACTOR_ID, channelIds: ["default"], skillIds: ["add_track", "adjust_instrument", "pattern_steps", "pattern_piano", "channel_mix"] }) ?? null);
        (ws.send(joinPayload) ?? null);
      }
    });
    (ws.onmessage = (e) => {
      {
        try {
          {
            let msg = (JSON.parse((String(e.data) ?? null)) ?? null);
            if ((msg.type === "control"))
              {
                if ((msg.op === "playing_start"))
                  {
                    (tplBuffer = []);
                  }
              }
            else
              if ((msg.type === "tpl.line"))
                {
                  if (msg.line)
                    (pushContextLine(msg.line) ?? null);
                }
              else
                if (((msg.type === "tpl.block") && (Array.isArray(msg.lines) ?? null)))
                  {
                    let i = 0;
                    while ((i < msg.lines.length))
                      {
                        (pushContextLine((msg.lines[i] ?? null)) ?? null);
                        (i = (i + 1));
                      }
                  }
          }
        } catch (err) {
          {
          }
        }
      }
    });
    (ws.onclose = (e) => {
      {
        (isConnected = false);
        let globalObj = ((((__v) => __v == null ? "null" : typeof __v)(globalThis) !== "undefined") ? globalThis : null);
        if ((globalObj && globalObj.setTimeout))
          {
            (globalObj.setTimeout(connectToGateway, 2000) ?? null);
          }
      }
    });
    (ws.onerror = (e) => {
      {
        (isConnected = false);
      }
    });
  }
}
(connectToGateway() ?? null);
function sendRpc (msgObj) {
  {
    let json = ((JSON.stringify(msgObj) ?? null) + "\n");
    (p.stdout.write(json) ?? null);
  }
}
function handleRequest (req) {
  {
    let method = req.method;
    let params = (req.params || {  });
    if ((method === "initialize"))
      {
        (sendRpc({ jsonrpc: "2.0", id: req.id, result: { protocolVersion: "2024-11-05", capabilities: { tools: {  } }, serverInfo: { name: "deckard-mcp-server", version: "1.0.0" } } }) ?? null);
      }
    else
      if ((method === "notifications/initialized"))
        {
        }
      else
        if ((method === "tools/list"))
          {
            (sendRpc({ jsonrpc: "2.0", id: req.id, result: { tools: [{ name: "get_session_tpl", description: "Returns the current live TPL (Tish Patch Language) state of the Deckard session. Use this to see what tracks and generators exist.", inputSchema: { type: "object", properties: {  }, required: [] } }, { name: "send_tpl_block", description: "Send a block of TPL to the live DAW. The TPL describes a track, instruments, or patterns. Make sure to prefix track IDs with the actor ID.", inputSchema: { type: "object", properties: { tplLines: { type: "array", items: { type: "string" }, description: "Array of valid TPL lines." } }, required: ["tplLines"] } }, { name: "send_direct", description: "Send a natural language instruction to the built-in autonomous agent.", inputSchema: { type: "object", properties: { instruction: { type: "string", description: "The natural language instruction, e.g. 'add a punchy hihat'" } }, required: ["instruction"] } }] } }) ?? null);
          }
        else
          if ((method === "tools/call"))
            {
              let name = params.name;
              let args = (params.arguments || {  });
              if ((!isConnected || !ws))
                {
                  (sendRpc({ jsonrpc: "2.0", id: req.id, result: { content: [{ type: "text", text: "Error: Not connected to the Deckard gateway yet." }], isError: true } }) ?? null);
                  return;
                }
              if ((name === "get_session_tpl"))
                {
                  let state = ((tplBuffer.length > 0) ? (tplBuffer.join("\n") ?? null) : "(empty session or playback not started)");
                  (sendRpc({ jsonrpc: "2.0", id: req.id, result: { content: [{ type: "text", text: state }] } }) ?? null);
                }
              else
                if ((name === "send_tpl_block"))
                  {
                    let lines = args.tplLines;
                    if (!(Array.isArray(lines) ?? null))
                      {
                        (lines = [(String(lines) ?? null)]);
                      }
                    let blockPayload = (JSON.stringify({ type: "tpl.block", actorId: ACTOR_ID, authorId: ACTOR_ID, lines: lines, effectivePerfStep: 0, asap: true }) ?? null);
                    (ws.send(blockPayload) ?? null);
                    (sendRpc({ jsonrpc: "2.0", id: req.id, result: { content: [{ type: "text", text: (("Successfully sent " + (String(lines.length) ?? null)) + " TPL lines to the session.") }] } }) ?? null);
                  }
                else
                  if ((name === "send_direct"))
                    {
                      let text = (String((args.instruction || "")) ?? null);
                      let directPayload = (JSON.stringify({ type: "direct", actorId: ACTOR_ID, authorId: ACTOR_ID, text: text }) ?? null);
                      (ws.send(directPayload) ?? null);
                      (sendRpc({ jsonrpc: "2.0", id: req.id, result: { content: [{ type: "text", text: ("Sent directive to agent: " + text) }] } }) ?? null);
                    }
                  else
                    {
                      (sendRpc({ jsonrpc: "2.0", id: req.id, error: { code: -32601, message: "Method not found" } }) ?? null);
                    }
            }
          else
            {
              if (req.id)
                {
                  (sendRpc({ jsonrpc: "2.0", id: req.id, error: { code: -32601, message: "Method not found" } }) ?? null);
                }
            }
  }
}
let stdinBuffer = "";
(p.stdin.setEncoding("utf8") ?? null);
(p.stdin.on("data", (chunk) => {
  {
    (stdinBuffer = (stdinBuffer + chunk));
    let n = (stdinBuffer.indexOf("\n") ?? null);
    while ((n >= 0))
      {
        let line = (stdinBuffer.substring(0, n) ?? null);
        (stdinBuffer = (stdinBuffer.substring((n + 1)) ?? null));
        if ((line.length > 0))
          {
            try {
              {
                let msg = (JSON.parse(line) ?? null);
                (handleRequest(msg) ?? null);
              }
            } catch (e) {
              {
              }
            }
          }
        (n = (stdinBuffer.indexOf("\n") ?? null));
      }
  }
}) ?? null);
